import type { Organization, NewsArticle, Event } from './types';

export const organizations: Organization[] = [
  {
    id: '1',
    name: 'Impesa',
    logoId: 'org-logo-1',
    type: 'startup',
    description: 'Pioneros en pagos móviles y soluciones de transacciones digitales en LATAM.',
    website: 'https.impesa.com',
    country: 'Costa Rica',
    verticals: ['pagos', 'lending'],
    stage: 'scaleup',
    needs: ['talent', 'pilots'],
    isMember: true,
    membershipTier: 'premium',
    createdAt: new Date('2018-03-15T09:00:00Z'),
    updatedAt: new Date('2023-11-20T14:30:00Z'),
  },
  {
    id: '2',
    name: 'FintechCo',
    logoId: 'org-logo-2',
    type: 'startup',
    description: 'Startup de IA para scoring de crédito alternativo enfocado en PyMEs.',
    website: 'https.fintechco.io',
    country: 'Costa Rica',
    verticals: ['lending', 'regtech'],
    stage: 'growing',
    needs: ['capital', 'regulation_support'],
    isMember: true,
    membershipTier: 'standard',
    createdAt: new Date('2021-01-20T10:00:00Z'),
    updatedAt: new Date('2024-01-15T11:00:00Z'),
  },
  {
    id: '3',
    name: 'Banco Nacional de Costa Rica',
    logoId: 'org-logo-3',
    type: 'bank',
    description: 'Institución financiera líder en Costa Rica, buscando innovación a través de alianzas con fintechs.',
    website: 'https.bncr.fi.cr',
    country: 'Costa Rica',
    verticals: ['pagos', 'lending', 'insurtech'],
    stage: 'scaleup',
    needs: ['pilots'],
    isMember: true,
    membershipTier: 'institucional',
    createdAt: new Date('2017-05-01T00:00:00Z'),
    updatedAt: new Date('2023-12-01T10:00:00Z'),
  },
  {
    id: '4',
    name: 'Carao Ventures',
    logoId: 'org-logo-4',
    type: 'investor',
    description: 'Fondo de capital de riesgo enfocado en startups tecnológicas en etapas tempranas en América Latina.',
    website: 'https.caraoventures.com',
    country: 'Costa Rica',
    verticals: ['wealthtech', 'lending'],
    stage: 'scaleup',
    needs: [],
    isMember: true,
    membershipTier: 'premium',
    createdAt: new Date('2019-08-10T00:00:00Z'),
    updatedAt: new Date('2023-10-05T18:00:00Z'),
  },
  {
    id: '5',
    name: 'Zunify',
    logoId: 'org-logo-5',
    type: 'startup',
    description: 'Plataforma de pagos y lealtad que unifica la experiencia de compra.',
    website: 'https.zunify.com',
    country: 'Costa Rica',
    verticals: ['pagos', 'wealthtech'],
    stage: 'growing',
    needs: ['talent', 'capital'],
    isMember: true,
    membershipTier: 'standard',
    createdAt: new Date('2022-02-01T00:00:00Z'),
    updatedAt: new Date('2024-01-10T16:00:00Z'),
  },
];

export const news: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'Fintech en Costa Rica: Crecimiento récord en el último trimestre',
    category: 'Ecosistema',
    date: '2024-03-15',
    imageId: 'news-image-1'
  },
  {
    id: 'news-2',
    title: 'Nuevas regulaciones para pagos digitales: Lo que necesitas saber',
    category: 'Regulación',
    date: '2024-03-10',
    imageId: 'news-image-2'
  },
  {
    id: 'news-3',
    title: 'Banco Nacional y FintechCo anuncian alianza estratégica',
    category: 'Alianzas',
    date: '2024-03-05',
    imageId: 'news-image-3'
  },
];

export const events: Event[] = [
  {
    id: 'evt-1',
    title: 'Fintech Summit 2024',
    description: 'El evento anual más grande del ecosistema fintech de Costa Rica. Conecta, aprende y haz negocios.',
    type: 'summit',
    mode: 'hybrid',
    startDateTime: new Date('2024-08-22T09:00:00Z'),
    endDateTime: new Date('2024-08-23T18:00:00Z'),
    location: 'Centro de Convenciones de Costa Rica',
    speakers: [{ name: 'Jane Doe', role: 'CEO', organization: 'FintechCo' }],
    isPublic: true,
    createdBy: 'admin-user-id',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'evt-2',
    title: 'Webinar: El Futuro de la IA en Finanzas',
    description: 'Un panel de expertos discute cómo la inteligencia artificial está transformando los servicios financieros.',
    type: 'webinar',
    mode: 'online',
    startDateTime: new Date('2024-07-15T16:00:00Z'),
    endDateTime: new Date('2024-07-15T17:30:00Z'),
    location: 'Online',
    speakers: [{ name: 'John Smith', role: 'CTO', organization: 'AI Solutions' }],
    isPublic: true,
    createdBy: 'admin-user-id',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
